package com.AK.RentHub.model;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "user_current_location")
public class UserCurrentLocation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "latitude", nullable = false)
    private double latitude;

    @Column(name = "longitude", nullable = false)
    private double longitude;

    @Column(name = "timestamp", nullable = false)
    private long timestamp;

    // Constructors, getters, setters will be generated by Lombok's @Data annotation
}
